# Generated by Django 4.2.3 on 2026-04-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='Online Course', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='mode',
            field=models.CharField(choices=[('audit', 'Audit'), ('honor', 'Honor'), ('beta', 'Beta')], default='audit', max_length=5),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='total_learners',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learner',
            name='social_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('choices', models.ManyToManyField(related_name='submissions', to='onlinecourse.choice')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='onlinecourse.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('grade', models.IntegerField(default=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='onlinecourse.question'),
        ),
    ]
